
threading:
  n_threads: 16
  task_window_height: 100
  task_window_width: 100

fractal:
  params:
    max_depth: 1000
    edge: 2

    initial_area:
      center_x: 0.0
      center_y: 0.0
      diameter: 4.0

    pixel_scale: 0.5
    image_refresh_rate_ms: 500

